---
all:
  vars:
    sys_public_ip: 192.168.200.10
    apt_update: False

  hosts:
    server:
      ansible_become: yes
      ansible_host: 172.16.10.20
      ansible_user: user
      ansible_password: 1234
      ansible_become_user: root
      ansible_become_password: 1234

  children:
    chains:
      children:
        infiltration_chain:
          hosts:
            far:
              ansible_become: yes
              ansible_host: 192.168.200.30
              ansible_user: user
              ansible_password: 1234
              ansible_become_user: root
              ansible_become_password: 1234

            near:
              ansible_become: yes
              ansible_host: 192.168.200.20
              ansible_user: user
              ansible_password: 1234
              ansible_become_user: root
              ansible_become_password: 1234
